export const gameConfig = {
  copy: {
    title: 'Revenge of the Eyecat',
    startPrompt: 'Use the joystick or arrow keys to move Eyecat.',
    startHint: 'Move Eyecat with the joystick, arrow keys, or WASD. Collect coins and keys, then rescue the cat.',
    creditsLabel: 'Credits',
    musicStartLabel: 'Music: On',
    musicOnLabel: 'Music: On',
    musicOffLabel: 'Music: Off',
  },
  assets: {
    background: '/backgrounds/lab-final-ruin-2.png',
    optionalBackgrounds: ['/backgrounds/lab-final-ruin.png', '/backgrounds/lab-ruin.png', '/backgrounds/lab-glow.png'],
    player: '/characters/player-eye-cat-plain.png',
    vacuum: '/characters/character-vacuum.png',
    hostage: '/characters/character-white-cat.png',
    coin: '/characters/character-coin.png',
    concept: '/concept/cassia-revenge-of-the-eyecat.jpg',
    music: '/audio/cassia-revenge-of-the-eyecat-remix.mp3',
  },
  concept: {
    title: 'Original Game Idea',
    subtitle: "Cassia's Revenge of the Eyecat concept",
    alt: "Cassia's Revenge of the Eyecat concept art",
    imageWidth: 430,
    imageHeight: 392,
  },
  credits: {
    studentName: 'Cassia',
    contestTitle: 'PIK Composition Contest 2026',
    contestUrl: 'https://youtube.com/playlist?list=PLhhleIn9mEjhNAztK55u86m13lu6xpqoM&si=9kGz8asDtaMO3Wy8',
    studentCredit: 'Original music and characters by Cassia',
    youtubeUrl: 'https://youtu.be/sr8MUHoempk?si=fSSh9eexR-s-zNS8',
    designerName: 'Le Binh Anh Nguyen',
    designerEmail: 'binhanhpiano96@gmail.com',
    developerCredit: 'Game design and development by Le Binh Anh Nguyen and Codex',
  },
  layout: {
    designWidth: 720,
    designHeight: 840,
    topBar: { x: 40, y: 24, width: 640, height: 56 },
    playfield: { x: 96, y: 108, width: 528, height: 528 },
    bottomControls: { x: 0, y: 696, width: 720, height: 144 },
    prompt: { x: 360, y: 610, width: 500 },
    eventPrompt: { x: 360, y: 628, width: 460 },
    buttons: {
      credits: { x: 40, y: 716, width: 92, height: 44 },
      music: { x: 152, y: 716, width: 92, height: 44 },
    },
    joystick: { x: 500, y: 738, radius: 62 },
    startArt: {
      eyecat: { x: 268, y: 390, size: 132 },
      hostage: { x: 452, y: 390, size: 118 },
    },
  },
  storageKeys: {
    musicEnabled: 'revengeOfTheEyecat.musicEnabled',
    workshopOpen: 'revengeOfTheEyecat.workshopOpen',
  },
} as const
